Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
    ~~~~~~~~~^
        nb,
        ^^^
    ...<4 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/asyncio/base_events.py", line 720, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
        cell, index, execution_count=self.code_cells_executed + 1
    )
  File "/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from datasets import get_dataset_config_names

# Define a function to fetch and print dataset configurations
def configs(dataset_name):
    configs = get_dataset_config_names(dataset_name)  # Fetch configurations
    print(f"No. of configs - {len(configs)}")  # Print number of configurations
    print(f"Names of configs - {configs}")  # Print configuration names

# Call the function with the dataset name
configs("ai4bharat/naamapadam")

------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mConnectionError[0m                           Traceback (most recent call last)
Cell [0;32mIn[3], line 10[0m
[1;32m      7[0m     [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mNames of configs - [39m[38;5;132;01m{[39;00mconfigs[38;5;132;01m}[39;00m[38;5;124m"[39m)  [38;5;66;03m# Print configuration names[39;00m
[1;32m      9[0m [38;5;66;03m# Call the function with the dataset name[39;00m
[0;32m---> 10[0m [43mconfigs[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mai4bharat/naamapadam[39;49m[38;5;124;43m"[39;49m[43m)[49m

Cell [0;32mIn[3], line 5[0m, in [0;36mconfigs[0;34m(dataset_name)[0m
[1;32m      4[0m [38;5;28;01mdef[39;00m[38;5;250m [39m[38;5;21mconfigs[39m(dataset_name):
[0;32m----> 5[0m     configs [38;5;241m=[39m [43mget_dataset_config_names[49m[43m([49m[43mdataset_name[49m[43m)[49m  [38;5;66;03m# Fetch configurations[39;00m
[1;32m      6[0m     [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mNo. of configs - [39m[38;5;132;01m{[39;00m[38;5;28mlen[39m(configs)[38;5;132;01m}[39;00m[38;5;124m"[39m)  [38;5;66;03m# Print number of configurations[39;00m
[1;32m      7[0m     [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mNames of configs - [39m[38;5;132;01m{[39;00mconfigs[38;5;132;01m}[39;00m[38;5;124m"[39m)

File [0;32m/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/datasets/inspect.py:164[0m, in [0;36mget_dataset_config_names[0;34m(path, revision, download_config, download_mode, dynamic_modules_path, data_files, **download_kwargs)[0m
[1;32m    108[0m [38;5;28;01mdef[39;00m[38;5;250m [39m[38;5;21mget_dataset_config_names[39m(
[1;32m    109[0m     path: [38;5;28mstr[39m,
[1;32m    110[0m     revision: Optional[Union[[38;5;28mstr[39m, Version]] [38;5;241m=[39m [38;5;28;01mNone[39;00m,
[0;32m   (...)[0m
[1;32m    115[0m     [38;5;241m*[39m[38;5;241m*[39mdownload_kwargs,
[1;32m    116[0m ):
[1;32m    117[0m [38;5;250m    [39m[38;5;124;03m"""Get the list of available config names for a particular dataset.[39;00m
[1;32m    118[0m 
[1;32m    119[0m [38;5;124;03m    Args:[39;00m
[0;32m   (...)[0m
[1;32m    162[0m [38;5;124;03m    ```[39;00m
[1;32m    163[0m [38;5;124;03m    """[39;00m
[0;32m--> 164[0m     dataset_module [38;5;241m=[39m [43mdataset_module_factory[49m[43m([49m
[1;32m    165[0m [43m        [49m[43mpath[49m[43m,[49m
[1;32m    166[0m [43m        [49m[43mrevision[49m[38;5;241;43m=[39;49m[43mrevision[49m[43m,[49m
[1;32m    167[0m [43m        [49m[43mdownload_config[49m[38;5;241;43m=[39;49m[43mdownload_config[49m[43m,[49m
[1;32m    168[0m [43m        [49m[43mdownload_mode[49m[38;5;241;43m=[39;49m[43mdownload_mode[49m[43m,[49m
[1;32m    169[0m [43m        [49m[43mdynamic_modules_path[49m[38;5;241;43m=[39;49m[43mdynamic_modules_path[49m[43m,[49m
[1;32m    170[0m [43m        [49m[43mdata_files[49m[38;5;241;43m=[39;49m[43mdata_files[49m[43m,[49m
[1;32m    171[0m [43m        [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mdownload_kwargs[49m[43m,[49m
[1;32m    172[0m [43m    [49m[43m)[49m
[1;32m    173[0m     builder_cls [38;5;241m=[39m get_dataset_builder_class(dataset_module, dataset_name[38;5;241m=[39mos[38;5;241m.[39mpath[38;5;241m.[39mbasename(path))
[1;32m    174[0m     [38;5;28;01mreturn[39;00m [38;5;28mlist[39m(builder_cls[38;5;241m.[39mbuilder_configs[38;5;241m.[39mkeys()) [38;5;129;01mor[39;00m [
[1;32m    175[0m         dataset_module[38;5;241m.[39mbuilder_kwargs[38;5;241m.[39mget([38;5;124m"[39m[38;5;124mconfig_name[39m[38;5;124m"[39m, builder_cls[38;5;241m.[39mDEFAULT_CONFIG_NAME [38;5;129;01mor[39;00m [38;5;124m"[39m[38;5;124mdefault[39m[38;5;124m"[39m)
[1;32m    176[0m     ]

File [0;32m/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/datasets/load.py:1731[0m, in [0;36mdataset_module_factory[0;34m(path, revision, download_config, download_mode, dynamic_modules_path, data_dir, data_files, cache_dir, trust_remote_code, _require_default_config_name, _require_custom_configs, **download_kwargs)[0m
[1;32m   1726[0m                 [38;5;28;01melse[39;00m:
[1;32m   1727[0m                     [38;5;28;01mraise[39;00m [38;5;167;01mFileNotFoundError[39;00m(
[1;32m   1728[0m                         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mCouldn[39m[38;5;124m'[39m[38;5;124mt find any data file at [39m[38;5;132;01m{[39;00mrelative_to_absolute_path(path)[38;5;132;01m}[39;00m[38;5;124m. [39m[38;5;124m"[39m
[1;32m   1729[0m                         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mCouldn[39m[38;5;124m'[39m[38;5;124mt find [39m[38;5;124m'[39m[38;5;132;01m{[39;00mpath[38;5;132;01m}[39;00m[38;5;124m'[39m[38;5;124m on the Hugging Face Hub either: [39m[38;5;132;01m{[39;00m[38;5;28mtype[39m(e1)[38;5;241m.[39m[38;5;18m__name__[39m[38;5;132;01m}[39;00m[38;5;124m: [39m[38;5;132;01m{[39;00me1[38;5;132;01m}[39;00m[38;5;124m"[39m
[1;32m   1730[0m                     ) [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;28;01mNone[39;00m
[0;32m-> 1731[0m             [38;5;28;01mraise[39;00m e1 [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;28;01mNone[39;00m
[1;32m   1732[0m [38;5;28;01melif[39;00m trust_remote_code:
[1;32m   1733[0m     [38;5;28;01mraise[39;00m [38;5;167;01mFileNotFoundError[39;00m(
[1;32m   1734[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mCouldn[39m[38;5;124m'[39m[38;5;124mt find a dataset script at [39m[38;5;132;01m{[39;00mrelative_to_absolute_path(combined_path)[38;5;132;01m}[39;00m[38;5;124m or any data file in the same directory.[39m[38;5;124m"[39m
[1;32m   1735[0m     )

File [0;32m/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/datasets/load.py:1618[0m, in [0;36mdataset_module_factory[0;34m(path, revision, download_config, download_mode, dynamic_modules_path, data_dir, data_files, cache_dir, trust_remote_code, _require_default_config_name, _require_custom_configs, **download_kwargs)[0m
[1;32m   1609[0m [38;5;28;01mexcept[39;00m LocalEntryNotFoundError [38;5;28;01mas[39;00m e:
[1;32m   1610[0m     [38;5;28;01mif[39;00m [38;5;28misinstance[39m(
[1;32m   1611[0m         e[38;5;241m.[39m__cause__,
[1;32m   1612[0m         (
[0;32m   (...)[0m
[1;32m   1616[0m         ),
[1;32m   1617[0m     ):
[0;32m-> 1618[0m         [38;5;28;01mraise[39;00m [38;5;167;01mConnectionError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mCouldn[39m[38;5;124m'[39m[38;5;124mt reach [39m[38;5;124m'[39m[38;5;132;01m{[39;00mpath[38;5;132;01m}[39;00m[38;5;124m'[39m[38;5;124m on the Hub ([39m[38;5;132;01m{[39;00me[38;5;241m.[39m[38;5;18m__class__[39m[38;5;241m.[39m[38;5;18m__name__[39m[38;5;132;01m}[39;00m[38;5;124m)[39m[38;5;124m"[39m) [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01me[39;00m
[1;32m   1619[0m     [38;5;28;01melse[39;00m:
[1;32m   1620[0m         [38;5;28;01mraise[39;00m

[0;31mConnectionError[0m: Couldn't reach 'ai4bharat/naamapadam' on the Hub (LocalEntryNotFoundError)

